### PR TITLE
Add docs for drive.watch

### PR DESCRIPTION
**Pull request by RangerMauve**
Also clarified that the update event doesn't get emitted unless you're watching files or downloading data.

### CODE REVIEW

**Comment by RangerMauve** [comment]
@andrewosh How does this README change look? :o I think it'd be handy for people trying to listen on updates.

**Comment by KyleAMathews** [comment]
Is there a way to get _what_ file changed? That's necessary when watching directories.

**Comment by RangerMauve** [comment]
@KyleAMathews To get the file that changed you'll want to diff against the previous version since that isn't being tracked AFAIK. @mafintosh or @andrewosh might have more insight though.

I usually use this for diffs: https://github.com/pfrazee/diff-file-tree

**Review by andrewosh — APPROVED** [review]

**Comment by andrewosh** [comment]
Thanks @RangerMauve, and sorry for missing this one!

**Pull request merged**
