### PR TITLE
Added destroy method

### PR DESCRIPTION
**Pull request by RangerMauve**
This just destroys the archive's metadata and content feed. Will look at adding a flag for destroying mounts in the near future.

### CODE REVIEW

**Comment by RangerMauve** [comment]
@mafintosh @andrewosh is there anything else to change here?

**Comment by RangerMauve** [comment]
Anything else I should do to get this in?

**Comment by andrewosh** [comment]
Hey @RangerMauve I'm really sorry this has taken an eternity, but let's get this in today. I'm gonna fix the Travis issue to turn this green, then rebase + publish.

Think it's totally fine to have this be a shallow deletion for now. There are a few other methods (like createDiffStream) that are shallow too, so it's not too confusing.

**Comment by andrewosh** [comment]
Published 10.11.0

**Comment by RangerMauve** [comment]
Awesome! Thank you. 💜

**Pull request merged**
